# hadolint ignore=DL3007
FROM ${BASE_IMAGE_NAME}:${BASE_IMAGE_VERSION}

COPY src/composer.json /home/circleci/

RUN composer install --prefer-dist && \
    composer clear-cache

# RUN composer global require codeception/codeception:2.5.4 && \
#    composer clear-cache

COPY src/codeception /home/circleci/codeception
COPY src/bin/codeceptionify.sh /usr/local/bin/codeceptionify.sh

ENV PATH="/home/circleci/vendor/bin:${PATH}"
